const loadingButton = document.querySelector('#loader')

function parseNodeDB(){
	return new Promise(async (resolve, reject) => {
		try {
		const info_text = document.querySelector('.information-layer-text')
		//Fetch Data from API for Terms and Hashtags
		if(setLang == "KR"){await axios.get('https://sheetdb.io/api/v1/2gjut6v25rdiy?sheet=kr&sort_by=level&sort_order=asc').then( response => {
			termDB = response.data;
			info_text.innerHTML = "<p>‘정의되지 않은 파노라마’(2018-현재)는 사회정치적 인프라와 시스템, 그리고 그 안에 내재된 관계를 탐구한다. 이 끊임없이 진화하는 프로젝트는 세계화, 사회 위기, 불평등, 경제, 정치의 영향으로 사람들이 어떻게 어려움을 겪는지를 생각하며 작가 함양아에 의해 수집된 연구에 기초하고 있다. 이 프로젝트의 목적은 사회가 어떻게 조직되어 있는지 관찰하는 것이며 돌봄과 연대에 기반한 사회구조에는 어떤 가능성이 있는가? 라는 질문을 하는 것이다. </p><p>‘정의되지 않은 파노라마’의 온라인 버전은 사람들이 세계, 국가, 지역에 대한 미시적인 것과 거시적인 관점 사이에서 움직일 수 있게 한다. 함양아는 이 스케일 사이를 이동하면서, 이러한 사건들과 우리의 관계에 대한 질문을 하고, 관찰의 스케일을 변화시킴으로써 새로운 의미를 만들어내고자 한다. ‘정의되지 않은 파노라마’는 어쩌면 보이지 않는 상태로 남을 수 있었던  큰 역사적 과정과 우리가 맺고 있는 관계를 볼 수 있게 해 준다. 이 웹 버전의 프로젝트에서, 작가는 이러한 관계를 열어 우리의 삶에  드리워진 그 관계에 대한 이야기를 하고 견해를 밝히고 질문을 할 수 있도록 초대한다.</p><p>‘정의되지 않은 파노라마’는 함양아와 노라 오 무르추, 마뉴엘 버거, 케일린 핀이 협업하고 이성민(기획자), 구예나(코디네이터), 파 갱(어시스턴트 리서처)과 함께 제작되었다.</p><p>이 웹프로젝트는 2022년 서서울미술관 사전 프로그램 《이례적인 시간, 불확실한 움직임》의 제작지원과 2022년 국제예술교류지원사업의 지원을 받았다.</p>"
			console.log("Success, data logged (terms)")
		})}else if(setLang == "ENG"){
			await axios.get('https://sheetdb.io/api/v1/2gjut6v25rdiy?sheet=Sheet1&sort_by=level&sort_order=asc').then( response => {
				termDB = response.data;
				info_text.innerHTML = "<p>Undefined Panorama (2018–present) explores socio-political infrastructures and systems, and the relations embedded within them. This continuously evolving project is based on research collected by the artist Yang Ah Ham as she observes how people deal with hardship generated by the impact of globalisation, societal crisis, inequality, economics, and politics in their lives. The aim of the project is to observe how society is organised and aims to ask: What possibilities are there for social structures based on care and solidarity? </p><p> The online version of Undefined Panorama allows people to move between micro and macro perspectives of global, national and local events. In moving between these scales, Yang Ah Ham aims to open up questions about our relations to these events, and to generate new meanings by altering the scale of observation. Undefined Panorama allows us to observe aspects of large historical processes and our relations to them that otherwise remain invisible. In this web version of the project, the artist opens up these relations to others and invites stories, comments and questions about their role in our lives. </p><p>Undefined Panorama is a project by Yang Ah Ham in collaboration with, The Laboratory of Manuel Bürger, Cailean Finn, and Nora O Murchú. The work was made with the support of curator SungMin LJ, assistant researcher Parr Geng, coordinator Yena Ku.</p><p>This website was commissioned by 2022 Seo-Seoul Museum of Art Pre-opening Public Program Exceptional Times, Uncertain Moves, and created with support from the Arts Council Korea.</p>"
				console.log("Success, data logged (terms)")
			});
		}
		
		

		//Organise each Dataset accordingly, so it can be understood by the sort function
		//document.getElementById("loader").style.display = "none";
		termDB = await fixTerms(termDB);
		termDB = await appendImageLink(termDB);
		console.log(termDB)
		await generate_links();
		resolve(termDB)
	}catch(error){
		reject(error)
	}
}	)
}

function fixTerms(initTerms){
     initTerms.forEach(node => {
        relationString = node.relations
        //relationString = relationString.replace(/\s+/g, '')
        node.relations = !relationString ? [] : relationString.split(",")
        for(var i = 0; i < node.relations.length; i++){
            node.relations[i] = node.relations[i].trim()
            
        }
        
    })
    console.log("Fixed Relations")
    return initTerms
}

function orderRelations(initTerms){
    initTerms.forEach(node => {
        node.relations = relatedTermsBubbleSort(node.relations)
    })
    return initTerms
}


function appendImageLink(imgArray){
    var urlToConcat = "./gifs/"
    imgArray.forEach(node => {
        imageStringInit = node.image
        node.image = urlToConcat.concat(imageStringInit)
        //node.image = "./gifs/culture.gif"
        node.level = parseInt(node.level)
    })
    console.log("Appeneded IMG URL")
    return imgArray
}
